iaso_playground_connector_slug = {
    "url": "https://iaso-playground.bluesquare.org",
    "username": "fernando_di_demo",
    "password": "13.5	19.5	10.5",
}

iaso_connector_slug = {
    "url": "https://iaso.bluesquare.org",
    "username": "fernando_diniger",
    "password": "hbe8quh1hjm*cyx6AQH",
}

iaso_form_id = 1186

dict_districts_cibles_iaso = {
    "Abala": "Abala",
    "Abalak": "Abalak",
    "Aderbissanat": "Aderbissinat",
    "Agadez commune": "Agadez",
    "Aguié": "Aguié",
    "Arlit": "Arlit",
    "Ayerou": "Ayorou",
    "Bagaroua": "Bagaroua",
    "Balleyara": "Balleyara",
    "Ballayara": "Balleyara",
    "Banibangou": "Banibangou",
    "Bankilare": "Bankilare",
    "Belbédji": "Belbedji",
    "Bermo": "Bermo",
    "Bilma": "Bilma",
    "Birni N'Konni": "Birni Konni",
    "Boboye": "Boboye",
    "Bosso": "Bosso",
    "Bouza": "Bouza",
    "Dakoro": "Dakoro",
    "Damagaram Takaya": "Damgaram Takaya",
    "Diffa": "Diffa",
    "Dioundou": "Dioundou",
    "Dogondoutchi": "Dogon Doutchi",
    "Dosso": "Dosso",
    "Dungass": "Doungass",
    "Falmey": "Falmey",
    "Filingue": "Fillingue",
    "Gaya": "Gaya",
    "Gazaoua": "Gazaoua",
    "Gotheye": "Gotheye",
    "Goudoumaria": "Goudoumaria",
    "Gouré": "Goure",
    "Guidan Roumdji": "Guidan Roumdji",
    "Iférouane": "Iferouane",
    "Illéla": "Illéla",
    "Ingall": "Ingall",
    "Keita": "Keita",
    "Kollo": "Kollo",
    "Loga": "Loga",
    "Madaoua": "Madaoua",
    "Madarounfa": "Madarounfa",
    "Magaria": "Magaria",
    "Mainé Soroa": "Mainé Soroa",
    "Malbaza": "Malbaza",
    "Maradi Ville": "Maradi Ville",
    "Kantché": "Matamèye",
    "Mayahi": "Mayahi",
    "Mirriah": "Mirriah",
    "N'Guigmi": "N'Guigmi",
    "N'gourti": "N'Gourti",
    "Niamey  I": "Niamey I",
    "Niamey  II": "Niamey II",
    "Niamey  III": "Niamey III",
    "Niamey  IV": "Niamey IV",
    "Niamey  V": "Niamey V",
    "Oullam": "Ouallam",
    "Say": "Say",
    "Tahoua Commune": "Tahoua Commune",
    "Tahoua Département": "Tahoua",
    "Tahoua Ville": "Tahoua Commune",  # unclear that's the case
    "Takeita": "Takeita",
    "Tanout": "Tanout",
    "Tassara": "Tassara",
    "Tchintabaraden": "Tchintabaraden",
    "Tchirozérine ": "Tchirozérine",
    "Tera": "Tera",
    "Tesker": "Tesker",
    "Tessaoua": "Tessaoua",
    "Tibiri (Doutchi)": "Tibiri",
    "Tillabéry": "Tillabery",
    "Tillia": "Tillia",
    "Torodi": "Torodi",
    "Zinder Ville": "Zinder Ville",
}
dict_districts_cibles_iaso = {
    key: f"DS {item}" for key, item in dict_districts_cibles_iaso.items()
}
