name: Push pipeline on OpenHEXA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Push pipeline to OpenHEXA
        uses: blsq/openhexa-push-pipeline-action@v1.0.0
        with:
          token: ${{ secrets.OH_TOKEN }}
          workspace: "pev-niger-7cc1fb"
          pipeline: "configure-new-campaign"